### ISSUE TITLE
Status freezes at testing when...

### ISSUE THREAD

**Issue by tyzess** [lunactic/DIVAServices#15]
Status freezes at testing when Algorithm is uploaded the second time (removed previously via DELETE route)

**Comment by lunactic** [comment]
The key issue here is that we need to figure out how to handle algorithms that once were deleted and are then added again....

Currently I set the status of a deleted algorithm to 'deleted'.

The easy possibility would be to just reuse the route and set the status of the algorithm to 'available' again. This opens one problem though:
What should we do with results coming from the 'old' algorithm?

**Comment by lunactic** [comment]
Partially fixed with 079d9b7

Open issues:
- Handling of changes in algorithm parameters
