### ISSUE TITLE
Add new route GET /algorithms/ID/status

### ISSUE THREAD

**Issue by tyzess** [lunactic/DIVAServices#5]
Return the newest status of the algorithm

If running: `{ "statusCode": 0, "statusMessage": "Algorithm is available" }`
If error during test-run: `{ "statusCode": 100, "statusMessage": "Error: <<Error message>>" }`
If currently building image: `{ "statusCode": 42, "statusMessage": "Building Algorithm" }`
... (to be extended)

**Comment by lunactic** [comment]
I will build you the following:

If creating: `{statusCode: 100, statusMessage: 'Building Algorithm Image'}`
If testing: `{statusCode: 110, statusMessage: 'Testing Algorithm'}`
If ok: `{statusCode: 200, statusMessage: 'Algorithm is Available'}`
If Error: `{statusCode: 500, statusMessage: 'Error: <<Error message>>'}`

**Comment by lunactic** [comment]
Solved in  6c905a7

The route is GET /algorithms/ID
