### ISSUE TITLE
Add DELETE /algorithms/ID to remove an existing algorithm

### ISSUE THREAD

**Issue by tyzess** [lunactic/DIVAServices#7]
Don't care about authentication yet

**Comment by lunactic** [comment]
started implementation in 5530396 needs some testing and improvements

**Comment by tyzess** [comment]
Hows the interaction? I guess a 200 if it could be deleted and otherwise a 500?
Or do you want to work via json responses? (always 200 but result in json)

**Comment by tyzess** [comment]
Calling DELETE /algorithm/id twice crashes the server

**Comment by tyzess** [comment]
@lunactic DELETE /algorithm/id never returns a response. Postman just says `loading..`. DIVAService says `[2016-04-30 12:26:58.390] [INFO] server - removing algorithm: 386817c01b75bb5fd91f4801ec5c639d7b0b4348
`

**Comment by lunactic** [comment]
@uzysset I think this is fixed in 87d2b65, right?

**Comment by tyzess** [comment]
Should be okay
